2020-06-23 14:28:18,761 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:20:44,849 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:21:14,939 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:21:40,927 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:21:50,595 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:53:26,793 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:54:15,675 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:55:36,497 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:56:13,190 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 15:57:33,378 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 16:13:11,027 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 16:13:15,621 ERROR: $(message)s [in /home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/me/bin/python/microblog/app/routes.py", line 73, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-06-23 16:13:18,215 ERROR: $(message)s [in /home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/me/bin/python/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/me/bin/python/microblog/app/routes.py", line 73, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-06-23 16:14:04,318 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 16:36:49,632 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 16:51:42,758 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-23 16:57:35,829 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-24 09:05:19,738 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:43]
2020-06-24 09:08:20,013 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:45]
2020-06-24 09:10:44,308 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:45]
2020-06-24 09:23:44,349 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:45]
2020-06-24 09:44:36,064 INFO: $(message)s [in /home/me/bin/python/microblog/app/__init__.py:45]
